import { Inter } from "next/font/google";
import "./globals.css";  // Ensure this path is correct
import Navbar from "./Components/Navbar";  // Check for correct casing in the path
import Provider from "./Components/ReactQueryProvider";
import { ReactNode } from "react";  // Import ReactNode type for children

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SAYNT AI",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;  // Type the children prop as ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full w-[100%] mx-auto`}>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
